#ifndef ERROR_H
#define ERROR_H

#include <stdint.h>
#include <base.h>

#define RETURN_EXTENDED_ERRORS true
#define RETURN_ACTION true

typedef enum
{
    ERR_NO_ERR = 0x00,
    ERR_INVALID_FUNCTION = 0x01,
    ERR_FILE_NOT_FOUND = 0x02,
    ERR_PATH_NOT_FOUND = 0x03,
    ERR_TOO_MANY_OPEN_FILES = 0x04,
    ERR_ACCESS_DENIED = 0x05,
    ERR_INVALID_HANDLE = 0x06,
    ERR_MCB_DESTROYED = 0x07,
    ERR_INSUFFICIENT_MEMORY = 0x08,
    ERR_INVALID_BLOCK_ADDRESS = 0x09,
    ERR_INVALID_ENVIRONMENT = 0x0A,
    ERR_INVALID_FORMAT = 0x0B,
    ERR_INVALID_ACCESS_MODE = 0x0C,
    ERR_INVALID_DATA = 0x0D,
    ERR_RESERVED_0E = 0x0E,
    ERR_INVALID_DRIVE = 0x0F,
    ERR_REMOVE_CURRENT_DIRECTORY = 0x10,
    ERR_NOT_SAME_DEVICE = 0x11,
    ERR_NO_MORE_FILES = 0x12,
    ERR_WRITE_PROTECTED_DISKETTE = 0x13,
    ERR_UNKNOWN_UNIT = 0x14,
    ERR_DRIVE_NOT_READY = 0x15,
    ERR_UNKNOWN_COMMAND = 0x16,
    ERR_CRC_ERROR = 0x17,
    ERR_BAD_REQUEST_LENGTH = 0x18,
    ERR_SEEK_ERROR = 0x19,
    ERR_UNKNOWN_MEDIA_TYPE = 0x1A,
    ERR_SECTOR_NOT_FOUND = 0x1B,
    ERR_PRINTER_OUT_OF_PAPER = 0x1C,
    ERR_WRITE_FAULT = 0x1D,
    ERR_READ_FAULT = 0x1E,
    ERR_GENERAL_FAILURE = 0x1F,
    ERR_SHARING_VIOLATION = 0x20,
    ERR_LOCK_VIOLATION = 0x21,
    ERR_INVALID_DISK_CHANGE = 0x22,
    ERR_FCB_UNAVAILABLE = 0x23,
    ERR_SHARING_BUFFER_OVERFLOW = 0x24,
    ERR_RESERVED_25 = 0x25,
    ERR_UNABLE_TO_COMPLETE_OPERATION = 0x26,
    ERR_RESERVED_27 = 0x27,
    ERR_RESERVED_28 = 0x28,
    ERR_RESERVED_29 = 0x29,
    ERR_RESERVED_2A = 0x2A,
    ERR_RESERVED_2B = 0x2B,
    ERR_RESERVED_2C = 0x2C,
    ERR_RESERVED_2D = 0x2D,
    ERR_RESERVED_2E = 0x2E,
    ERR_RESERVED_2F = 0x2F,
    ERR_RESERVED_30 = 0x30,
    ERR_RESERVED_31 = 0x31,
    ERR_NETWORK_REQ_NOT_SUPPORTED = 0x32,
    ERR_REMOTE_NOT_LISTENING = 0x33,
    ERR_DUPLICATE_NAME = 0x34,
    ERR_NETWORK_NAME_NOT_FOUND = 0x35,
    ERR_NETWORK_BUSY = 0x36,
    ERR_DEVICE_NO_LONGER_EXISTS = 0x37,
    ERR_NETBIOS_COMMAND_LIMIT = 0x38,
    ERR_NETWORK_ADAPTER_ERROR = 0x39,
    ERR_INCORRECT_NETWORK_RESPONSE = 0x3A,
    ERR_UNEXPECTED_NETWORK_ERROR = 0x3B,
    ERR_INCOMPATIBLE_REMOTE_ADAPTER = 0x3C,
    ERR_PRINT_QUEUE_FULL = 0x3D,
    ERR_NO_SPACE_FOR_PRINT_FILE = 0x3E,
    ERR_PRINT_FILE_DELETED = 0x3F,
    ERR_NETWORK_NAME_DELETED = 0x40,
    ERR_NETWORK_ACCESS_DENIED = 0x41,
    ERR_NETWORK_DEVICE_TYPE_INCORRECT = 0x42,
    ERR_NETWORK_NAME_NOT_FOUND2 = 0x43,
    ERR_NETWORK_NAME_LIMIT_EXCEEDED = 0x44,
    ERR_NETBIOS_SESSION_LIMIT = 0x45,
    ERR_TEMPORARILY_PAUSED = 0x46,
    ERR_REQUEST_NOT_ACCEPTED = 0x47,
    ERR_REDIRECTION_PAUSED = 0x48,
    ERR_RESERVED_49 = 0x49,
    ERR_RESERVED_4A = 0x4A,
    ERR_RESERVED_4B = 0x4B,
    ERR_RESERVED_4C = 0x4C,
    ERR_RESERVED_4D = 0x4D,
    ERR_RESERVED_4E = 0x4E,
    ERR_RESERVED_4F = 0x4F,
    ERR_FILE_ALREADY_EXISTS = 0x50,
    ERR_RESERVED_51 = 0x51,
    ERR_CANNOT_MAKE_DIR_ENTRY = 0x52,
    ERR_FAIL_ON_INT24 = 0x53,
    ERR_TOO_MANY_REDIRECTIONS = 0x54,
    ERR_DUPLICATE_REDIRECTION = 0x55,
    ERR_INVALID_PASSWORD = 0x56,
    ERR_INVALID_PARAMETER = 0x57,
    ERR_NETWORK_DEVICE_FAULT = 0x58,
    ERR_NETWORK_FN_NOT_SUPPORTED = 0x59,
    ERR_COMPONENT_NOT_INSTALLED = 0x5A,
    ERR_INVALID_ARGS = 0x5B,
} error_t;

typedef enum
{
    ACTION_NO_ACTION = 0x00,
    ACTION_RETRY = 0x01,              // retry a few more times and re-prompt
    ACTION_DELAY_RETRY = 0x02,        // delay retry after a pause
    ACTION_REENTER_INPUT = 0x03,      // prompt user to re-enter input
    ACTION_ABORT_WITH_CLEANUP = 0x04, // orderly abort and shutdown
    ACTION_IMMEDIATE_ABORT = 0x05,    // immediate abort
    ACTION_IGNORE = 0x06,             // ignore the error
    ACTION_USER_INTERVENTION = 0x07,  // retry after user fixes problem
    ACTION_FIX_ARGS = 0x08            // fix the function arguments
} action_t;

#ifdef INSIDE_GRITTY
error_t errnum = ERR_NO_ERR;
action_t action = ACTION_NO_ACTION;
#else
extern error_t errnum;
extern action_t action;
#endif // INSIDE_GRITTY

const char *errToString(error_t errnum);
const char *actionToString(action_t action);

#endif